### ISSUE TITLE
Help Understanding NUM_NEURAL_DIMS

### ISSUE THREAD

**Issue by ryanmaxwell96** [kevin-fang/reinforced-flappy-bird#3]
Hello,

Could someone please help me understand where NUM_NEURAL_DIMS is coming from? I tried to do a Google search as well as look through the folders and couldn't find it. 

Thanks,
Ryan

**Comment by kevin-fang** [comment]
It's been a while since I've looked at this code, but I believe NUM_NEURAL_DIMS is just the number of inputs from each training sample, as in the number of input neurons in the network.

**Comment by ryanmaxwell96** [comment]
Wow, thank you so much for the fast reply. Actually I was first using Pytorch, but swapped to Tensorflow because I figured Tensorflow had a wider support network.

At any rate, I'm just trying to figure out where specifically is it getting defined or from which package so as to understand how the code is working better. It isn't hard to see how it is being used in the FlappyGraph function. But where is it coming from? It has to be random, sys, numpy, config, tensorflow, tf_graph, os or sklearn but I haven't found it. Plus, if you have any suggestions as to what other websites are helpful to get live support for newbies, that would be highly appreciated!

**Comment by kevin-fang** [comment]
The variable is being defined in `config.py` (https://github.com/kevin-fang/reinforced-flappy-bird/blob/master/FlappyBird/config.py).

I highly suggest reading Karpathy's blog post [Deep Reinforcement Learning: Pong from Pixels](http://karpathy.github.io/2016/05/31/rl/), as it's where I got a lot of my inspiration and he explains it and the math behind it really well. He writes it in pure numpy, though, so it may be a little more difficult to understand.

**Comment by ryanmaxwell96** [comment]
Ok well thanks again so much for the help! I don't want to ask too much, but do you think you will be available to help with understanding this code if I have any other questions in the code? And thanks for the suggestion about Karpathy's blog. I will be sure toe look it up.
